### ISSUE TITLE
Naruto and other Anime - no subtitles?

### ISSUE THREAD

**Issue by kpaskevicius** [sheodox/jimaku-player#25] opened 2021-06-02 21:20 UTC
I'll leave this comment here as I'm trying to figure out why the subtitles worked in some anime on VRV, but not Naruto or others I'm trying. I'm using subtitles from :https://www.kitsunekko.net/

Please let me know if there may be anything I'm doing wrong with your tools. 
Again, it seemed to work with the Kimetsu show, but not some others.

I used an SRT file for the 1st episode and didn't receive any subtitles to play with.

**Comment by sheodox** [comment] 2021-06-02 21:28
Hmm, a regular SRT file shouldn't have anything funky with it. Did you get an error popup when you selected the subtitle file? I just tried some Naruto subtitles and they worked fine for me.

Could you check the settings you've got? There are some pretty easy to hit hotkeys, you might have accidentally hit one. In the Settings tab on the panel on the right side of the page can you make sure "Show subs over video" is checked? 

![image](https://user-images.githubusercontent.com/3468630/120554503-70964c00-c3bf-11eb-8dec-e93ae0af066b.png)

**Comment by kpaskevicius** [comment] 2021-06-02 21:31
I’ll double check, it was turned off, but turning on didn’t seem to change anything.
No errors , kimetsu was working, but naruto hasn’t been as of yet.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: sheodox ***@***.***>
Sent: Wednesday, June 2, 2021 5:29:12 PM
To: sheodox/jimaku-player ***@***.***>
Cc: Paskevicius, Kevin Brennen ***@***.***>; Author ***@***.***>
Subject: [External]Re: [sheodox/jimaku-player] Naruto and other Anime - no subtitles? (#25)


Hmm, a regular SRT file shouldn't have anything funky with it. Did you get an error popup when you selected the subtitle file? I just tried some Naruto subtitles and they worked fine for me.

Could you check the settings you've got? There are some pretty easy to hit hotkeys, you might have accidentally hit one. In the Settings tab on the panel on the right side of the page can you make sure "Show subs over video" is checked?

[image]<https://user-images.githubusercontent.com/3468630/120554503-70964c00-c3bf-11eb-8dec-e93ae0af066b.png>

**Comment by sheodox** [comment] 2021-06-02 21:40
I take it back. I tried with a different subtitle file and I'm seeing the issue you're describing. I'll look into this, thanks!

**Comment by kpaskevicius** [comment] 2021-06-02 21:43
Thanks for the hard work. Here is a photo of aligning subtitles as well. I see the correct subtitle line the middle, but it is unclickable. 

(correct for the timeframe on the video.)

Is there a way to click it?

![image](https://user-images.githubusercontent.com/85258902/120556055-fc14da80-c3c9-11eb-9044-9c2a831b9925.png)

**Comment by sheodox** [comment] 2021-06-02 22:16
The idea with the alignment working that way is that by the time you hear a subtitle you can search for it's too late to time your click right. If you clicked after searching your subtitles would be a second or more late, unless you were to rewind. The idea was you'd search while the show is playing, then look at the next line and when you hear someone just start saying that next line you'd click the button and it'd be timed perfectly.

I just released a new version that includes a fix for this issue. Get the update and let me know if it works!
You can force Tampermonkey to check for updates by clicking "Check for userscript updates" in the Tampermonkey menu:
![image](https://user-images.githubusercontent.com/3468630/120559003-e2719400-c3c5-11eb-957b-e1dff6081750.png)

The cause of the bug was some weird line endings. I'm not sure how they got the way they are in that file but I added a workaround to account for these strange line endings. Jimaku Player could only read one single blank subtitle because it couldn't figure out where one subtitle started and another began. Should hopefully be better now!

**Comment by kpaskevicius** [comment] 2021-06-02 22:48
Yeah that definitely helped with the subtitles (which was the main problem here).

Nice Work!

By the way, do you recommend a website for subtitles to work well with your tools?

**Comment by sheodox** [comment] 2021-06-02 22:55
Thanks! Glad it fixed your issue!

Nah, I think it's more dependent on the subtitles themselves. You'll find very different subtitles based on the show and who made them generally moreso than where you get them, I've only tested a handful of shows so far so development depends very much on what issues other people report or whenever I happen to branch out to a new show (which I haven't done in a while, One Piece is really long lol).

**Closed by sheodox** 2021-06-02 22:55 UTC

**Comment by kpaskevicius** [comment] 2021-06-02 22:57
Yeah, it really helps us language learners since it's hard to find a place to put the video and subtitles together this nicely. Well done
